version: '3.8'
services:
 db:
  image: postgres:9.4.4
  volumes:
    - ./tmp/db:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
 web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/pomoproOnRails
  ports:
    - "3000:3000"
  depends_on:
    - db
