web:
  image: wagnertrindade/pomopro:latest
  command: bash -c "rm -f /var/app/tmp/pids/server.pid && /var/app/script/bootstrap"
  restart: always
  working_dir: /var/app
  volumes:
    - .:/var/app
  links:
    - db
  ports:
   - "80:3000"
  environment:
    POSTGRES_URL: db
db:
  image: postgres:9.4.4
  expose:
    - '5432'
  volumes:
    - wt-postgres:/var/lib/postgresql/data
